### ISSUE TITLE
GSM 7-bit showing pointer value instead of GSM 7-bit encoding

### ISSUE THREAD

**Issue by itsursujit** [NiceLabs/go-smpp#1]
When I run tests, it works fine but I feel like something is wrong with detecting GSM 7-bit

```go
for _, multipart := range multipartList {
		expected := strings.Join(multipart, "")
		coding := BestCoding(expected)
		fmt.Println(coding.String())
		fmt.Println(coding.Encoding()) 
                // Shouldn't it show GSM 7-bit like it's showing for others?
                // Currently it's showing {0x14695d0 0x14695d0}
		splitter := coding.Splitter()
		segments := splitter.Split(expected, limit)
		require.Equal(t, multipart, segments)
		encoder := coding.Encoding().NewEncoder()
		for _, segment := range segments {
			require.LessOrEqual(t, splitter.Len(segment), limit)
			encoded, err := encoder.Bytes([]byte(segment))
			require.NoError(t, err)
			require.Equal(t, splitter.Len(segment), len(encoded), segment)
		}
	}
```
<img width="452" alt="Screen Shot 2020-10-06 at 00 01 10" src="https://user-images.githubusercontent.com/4959215/95116814-54c2a380-0767-11eb-9313-e2d15f6eb02b.png">

**Comment by septs** [comment]
you need via data coding value check coding name.

**Comment by septs** [comment]
The specification does not specify how to display the code name to the user.

![image](https://user-images.githubusercontent.com/3842474/95149213-ed810f80-07b7-11eb-9329-1b81c7d8db50.png)
(SMPP v5, pp. 123)

**Comment by septs** [comment]
@itsursujit If can hope to report some oem known issue notes and workaround.
https://github.com/NiceLabs/go-smpp/blob/master/docs/oem-known-issue-notes.md
